### PR TITLE
filter file open dialogbox

### PR DESCRIPTION
**Pull request by THausherr**
Show only relevant files, i.e. eml and msg.

### CODE REVIEW

**Comment by nickrussler** [comment]
Thanks for the PR! Is the acceptAllFileFilter still choosable?

**Comment by THausherr** [comment]
Sorry I don't understand. There is a class with that name but it's not helpful here. I just wanted something so that I can immediately see the relevant file, without having to type "*eml" every time.

**Comment by nickrussler** [comment]
I checked the documentation and it seems that you add a file filter and not replace the default "all files" one. I wanted to confirm if after your change this "all files" option is still available

**Comment by THausherr** [comment]
> I checked the documentation and it seems that you add a file filter and not replace the default "all files" one. I wanted to confirm if after your change this "all files" option is still available

Surprisingly: yes. I get shown an element "Alle Dateien" which means "all files".

grafik

**Comment by nickrussler** [comment]
Perfect, that's how it should be imho

**Comment by nickrussler** [comment]
The build failed, I guess the import is missing

**Comment by THausherr** [comment]
Sorry, I realize now I should have amended the PR, but I deleted the branch. Please add `import javax.swing.filechooser.FileNameExtensionFilter;`.

**Pull request merged**
